apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-word-api
spec:
  selector:
    matchLabels:
      app: number-word
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: number-word
        tier: backend
        track: stable
    spec:
      containers:
        - name: number-word-api
          image: numberwordapi
          ports:
            - name: http
              containerPort: 80