apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-word-api
spec:
  selector:
    matchLabels:
      app: number-word
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: number-word
        tier: backend
        track: stable
    spec:
      containers:
        - name: number-word-api
          image: numberwordapi:v1
          ports:
            - name: http
              containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: number-word-api
spec:
  selector:
    app: number-word
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31300
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-word-web
spec:
  selector:
    matchLabels:
      app: number-word
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: number-word
        tier: frontend
        track: stable
    spec:
      containers:
      - name: number-word-web
        image: numberwordweb:prod-v1
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
---
kind: Service
apiVersion: v1
metadata:
  name: number-word-web
spec:
  selector:
    app: number-word
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31200
  type: LoadBalancer