version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:198.0.0-alpine
    steps:
      - checkout      

      # build and push Docker image
      - run:
          name: Build config
          command: |
            bash ./config.sh

      - run:
          name: Deploy
          command: bash ./deploy-gcloud.sh
      