kind: Service
apiVersion: v1
metadata:
  name: number-word-api
spec:
  loadBalancerIP: 40.71.170.36
  selector:
    app: number-word
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31300
  type: LoadBalancer
