apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: number-word-api
spec:
  selector:
    matchLabels:
      app: number-word
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: number-word
        tier: backend
        track: stable
    spec:
      containers:
      - name: number-word-api
        image: baron123.azurecr.io/number-word/numberwordapi:{apiVersion}
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80