kind: Service
apiVersion: v1
metadata:
  name: number-word-web
spec:
  loadBalancerIP: 52.191.209.44
  selector:
    app: number-word
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31200
  type: LoadBalancer